<?php
//
// ETS2MP Homepage language file.
// File:				dutch.php
// Language name: 		Dutch
// Translated name: 	Nederlands
//

$_lang["download"] = "Download";
$_lang["home"] = "Home";
$_lang["status"] = "Status";
$_lang["username"] = "Gebruikersnaam";
$_lang["password"] = "Wachtwoord";
$_lang["login"] = "Login";
$_lang["register"] = "Registreren";
$_lang["download.latest.version"] = "Download de laatste versie";
$_lang["current.release"] = "Huidige versie";
$_lang["language"] = "Taal";
$_lang["join"] = "MEESPELEN";
$_lang["mainpage.join"] = "Speel mee met duizenden fanatieke truckers online!";
$_lang["ts3.advertisement"] = "Praten met andere truckers - klik hier om naar onze TS3 server te gaan.";
$_lang["facebook.advertisement"] = "Laatste nieuws op onze facebook.";
$_lang["registration.blocked"] = "Registreren tijdelijk geblokkeerd - We zijn bezig met ontwikkelingen waardoor we registratie tijdelijk uit moeten zetten. We zullen de blokkade stopzetten wanneer dit weer verantwoord is.";
$_lang["invalid.username.password"] = "Onjuiste gebruikersnaam of wachtwoord.";
$_lang["already.logged"] = "Je bent reeds ingelogd.";
$_lang["welcome"] = "Welkom";
$_lang["logout"] = "Uitloggen";
$_lang["bans"] = "Bans";
$_lang["version"] = "Versie";
$_lang["update.time"] = "Laatst geupdate";
$_lang["req.game.version"] = "Vereiste spel-versie";
$_lang["requires"] = "Vereist";
$_lang["or.newer"] = "of nieuwer";
$_lang["game.client"] = "Spel-Client";
$_lang["download.no.permissions"] = "Om de mod te downloaden, moet je ingelogd zijn.";
$_lang["why.create.account"] = "Waarom een account aanmaken?<br />Je account wordt gebruikt om in te loggen bij al onze diensten (forum, in-game, statistieken en meer). We zijn binnenkort van plan een economie en statistieken te introduceren. Je kunt ten allen tijdeb je profiel aanpassen.";
$_lang["website.title"] = "ETS2MP - Virtuele Truckers Wereld - Multiplayer mod voor Euro Truck Simulator 2, spel door SCS Software";
$_lang["cookies.warning"] = "Deze website gebruikt <a href=\"http://en.wikipedia.org/wiki/HTTP_cookie\">cookies</a>. Door deze website te gebruiken, gaat u akkoord met het gebruik van cookies.";
$_lang["forum"] = "Forum";
$_lang["cannot.create.account.when.logged"] = "Je kan geen account maken als je bent ingelogd.";
$_lang["successfully.registered"] = "Je bent succesvol geregistreerd."; 
$_lang["error.unknown"] = "Onbekende fout";
$_lang["credentials.taken"] = "Gebruikersnaam, email of steamID is al in gebruik.";
$_lang["error.no.steam.data"] = "Om een ETS2MP account aan te maken moet je ETS2 in je bezit hebben op Steam. Als je het spel bezit, controleer dan of je profiel publiek toegankelijk is. Als het privaat is moet je het publiek maken en druk op";
$_lang["register.steam.info"] = "Om te registreren moet je inloggen op je Steam account. Klik op de gele knop om door te gaan naar de login pagina van Steam.";
$_lang["rules.info"] = "Bij het registreren gaat u automatisch akkoord met de Gemeenschaps regels. Om de regels te bekijken klik dan hier..";
$_lang["mail"] = "Email";
$_lang["repeat.mail"] = "Herhaal e-mail";
$_lang["new.password"] = "Nieuw wachtwoord";
$_lang["repeat.new.password"] = "Herhaal nieuw wachtwoord";
$_lang["old.password"] = "Oud wachtwoord";
$_lang["repeat.old.password"] = "Herhaal oud wachtwoord";
$_lang["save.account.data"] = "Sla profiel gegevens op";
$_lang["edit.account"] = "Verander profiel";
$_lang["forgot.password"] = "Wachtwoord vergeten? Klik <a href=\"index.php?page=resetPassword\">hier</a>.";
$_lang["forgot.password.summary"] = "Wachtwoord vergeten? Schrijf uw e-mail op en druk op de \"Wachtwoord reminder\" knop.";
$_lang["reminder.button"] = "Wachtwoord reminder";
$_lang["reset.password"] = "Reset wachtwoord";
$_lang["password.reminder.mail.title"] = "Wachtwoord reminder";
$_lang["password.reminder.content"] = "Beste,\n\nIemand met het IP-adres: {0} Heeft een aanvraag ingediend om uw wachtwoord te veranderen van uw ETS2MP Profiel .\n\nOm uw wachtwoord te veranderen klik op deze link: {1}.\nZo niet, Negeer dan deze e-mail.\n\nMet vriendelijke groet,\nETS2MP Team";
$_lang["new.password.mail.title"] = "Je nieuwe wachtwoord.";
$_lang["new.password.mail.content"] = "Beste,\n\nDit is je  wachtwoord: {0}\n\nVergeet niet om het te veranderen na uw eerste login\n\nMet vriendelijke groet\nETS2MP Team";
$_lang["account.activated"] = "Uw profiel is succesvol geactiveerd";
$_lang["unable.to.activate"] = "Profiel activatie onmogelijk, ongeldige code of uw account is al reeds geactiveerd.";
$_lang["not.activated"] = "Je account is nog niet geactiveerd.Als u geen activatie code heeft ontvangen klik dan <a href=\"index.php?action=resendActivation\">hier</a> om de code nogmaals te ontvangen.";
$_lang["force.password.change"] = "Verander nu meteen uw wachtwoord. Klik  <a href=\"index.php?page=editAccount\">hier</a> om te doen";
$_lang["forgot.password.link.sent"] = "Bekijk je e-mail. We hebben je een wachtwoord-herstel verstuurd.";
$_lang["forgot.password.sent"] = "Bekijk je e-mail, we hebben je een nieuwe wachtwoord verstuurd";
$_lang["forgot.password.invalid.key"] = "Ongeldig wachtwoord.";
$_lang["activation.key.resent"] = "Nieuw activatie nummer is naar uw E-mail verstuurd.";
$_lang["activation.mail.title"] = "ETS2MP profiel activatie";
$_lang["activation.mail.content"] = "Beste,\n\nDit is je activatie nummer: {0}\n\nMet vriendelijke groet,\nETS2MP Team";
$_lang["no.login"] = "Je dient ingelogd te zijn om deze pagina te kunnen zien.";
$_lang["settings.saved.with.mail"] = "Profiel is opgeslagen. Bekijk je e-mail en activeer je profiel opnieuw.";
$_lang["new.mail.in.use"] = "Dit E-mail adres is al in gebruik.";
$_lang["mail.does.not.match"] = "Opgegeven e-mail adressen zijn niet hetzelfde";
$_lang["invalid.email.format"] = "E-Mail is niet geldig";
$_lang["new.password.does.not.match"] = "Nieuw wachtwoord komt niet overeen.";
$_lang["too.short.password"] = "Nieuw wachtwoord is te kort. Minimaal: 5 tekens.";
$_lang["old.password.does.not.match"] = "Oud wachtwoord is niet hetzelfde";
$_lang["settings.saved"] = "Profiel is opgeslagen.";
$_lang["invalid.old.password"] = "Oud wachtwoord is niet geldig,Onmogelijk om profiel op te slaan.";
$_lang["no.password.change.forced"] = "Om je wachtwoord te resetten dien je uitgelogd te zijn.";
$_lang["password.reminder.edit.account"] = "Wachtwoord vergeten? Klik <a href=\"index.php?page=resetPassword\">hier</a>.";
$_lang["contact"] = "Contact";
$_lang["your.mail"] = "Jouw e-mail";
$_lang["content"] = "Inhoud";
$_lang["send"] = "Verstuur";
$_lang["contact.message.sent"] = "Bedankt voor je aanvraag. Graag je geduld voor een antwoord.";
$_lang["topic"] = "Onderwerp";
$_lang["contact.message.too.short"] = "Het bericht is te kort. Minimaal 10 karakters.";
$_lang["contact.topic.too.short"] = "Het onderwerp is te kort. Minimaal 10 karakters.";
$_lang["steamid.in.use"] = "Wij hebben een ETSMP account gevonden die verbonden is met dit steam account. Wanneer je enige problemen ondervindt met registreren neem dan contact met ons op: <a href=\"http://ets2mp.com/index.php?page=contact\">contact</a>.";
$_lang["mail.does.not.match"] = "Opgegeven email adres komt niet overeen.";
$_lang["support"] = "Support";
$_lang["profile"] = "Profiel";
$_lang["group"] = "Groep";
$_lang["banned"] = "Banned";
$_lang["state"] = "Status";
$_lang["account.is.activated"] = "Account is geactiveerd.";
$_lang["account.isnt.activated"] = "Account is niet geactiveerd.";
$_lang["penalty.history"] = "Geschiedenis van overtredingen.";
$_lang["no.punishments"] = "Geen overtredingen om weer te geven.";
$_lang["date"] = "Datum";
$_lang["reason"] = "Reden";
$_lang["type"] = "Type";
$_lang["penalty.limit"] = "Alleen de eigenaar van dit profiel kan verdere historie of penalties zien.";
